routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {	
  return redirect('/login');
});

Auth::routes();
Route::get('/getproduct', 'ProductController@getProduct');
Route::group(['middleware' => 'auth'], function () {
	Route::resource('location', 'LocationController', ['except' => ['show']]);
	Route::resource('product', 'ProductController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

	Route::get('users','UserController@index')->name('user.index');
	Route::post('user/store','UserController@store')->name('user.store');
	Route::post('user/update','UserController@update')->name('user.update');
	Route::get('user/pop-up-data','UserController@editPopupData')->name('user.edit_popup');
	Route::post('user/delete','UserController@delete')->name('user.delete');
	Route::get('tasks','TaskController@index')->name('task.index');
	Route::get('tasksFilter','TaskController@tasksFilter')->name('task.filter');
	Route::get('task/addNewTask','TaskController@addNewTask')->name('task.new_task');
	Route::get('cityUser/{id}','TaskController@getCityUser')->name('cityUser');
	Route::get('cityAddress/{id}','TaskController@getCityAddress')->name('cityAddress');
	Route::get('roomType/{address}','TaskController@getroomType')->name('roomType');
	Route::get('getUserId/{addressId}','TaskController@getUserId')->name('getUserId');
	Route::post('task/store','TaskController@store')->name('task.store');
	Route::post('changeStatus','TaskController@changeStatus')->name("task.changeStatus");
	Route::post('updateSubTask','TaskController@updateSubTask')->name('updateSubTask');
	Route::get('deleteSubTask/{id}/{taskId}','TaskController@deleteSubTask')->name('deleteSubTask');
	Route::post('exportTask','TaskController@exportTask')->name('exportTask');
	Route::get('locations','LocationController@index')->name('location.index');
	Route::post('location/store','LocationController@store')->name('location.store');
	Route::post('location/update','LocationController@update')->name('location.update');
	Route::post('location/delete','LocationController@delete')->name('location.delete');
	Route::get('rooms','RoomController@index')->name('room.index');
	Route::post('room/store','RoomController@store')->name('room.store');
	Route::post('room/update','RoomController@update')->name('room.update');
	Route::post('room/delete','RoomController@delete')->name('room.delete');
	Route::post('exportTasks','TaskController@exportTasks')->name('exportTasks');

});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
class Product extends Model
{
  use Notifiable;
  protected $fillable = [
    'location_id', 'product_id','center_name','address',
  ];
  
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Location;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Oseintow\Shopify\Facades\Shopify;
class ProductController extends Controller
{
  protected $api_key;
  protected $password;
  protected $shop_url;
  protected $secret_key;
 
  public function __construct() {
    $this->api_key = env('SHOPIFY_APIKEY');
    $this->password = env('SHOPIFY_PASSWORD');
    $this->secret_key = env('SHOPIFY_SECRET');
    $this->shop_url = env('SHOPIFY_SHOP_URL');
  }

  public function index(Product $model,Request $request)
  {
    $shopify=$this->getShopifyObject();
    $shopify_products1 = $shopify->get("admin/products.json", ['fields'=>'id,title,variants',"page" => 1, "published_status"=>"published"]);
    $shopify_products = json_decode($shopify_products1,true);
    foreach($shopify_products as $key=>$eachProduct){
      $product_list = Product::join('locations','locations.id','=','products.location_id')->where('product_id', strval($eachProduct['id']))->get();

      foreach($product_list as $eachRecord){
        $shopify_products[$key]['location_details'][] = array(
          'location_id' => $eachRecord->location_id, 
          'center_name' => $eachRecord->center_name, 
          'address' => $eachRecord->address 
        );
      }  
    }
    $shopify_products=json_decode(json_encode($shopify_products), FALSE);

    $location_list = Location::all();
    return view('product.index', compact('shopify_products','location_list'));
  }

  public function create(Request $request)
  {
    $product_id=$request->query('product_id');
    $product_name=$request->query('product_name');
    $map_location_id = DB::table('products')->select('location_id')->where('product_id',$product_id)->get(); 
    //$location_list = Location::all();
    $active_location_list = Location::all()->where('location_status','Active');
    $active_location_list = Location::all()->where('location_status','Active');
    $inactive_location_list = Location::all()->where('location_status','Inactive');
    return view('product.create', compact('active_location_list','inactive_location_list','product_name','map_location_id','product_id'));
  }

  public function store(Request $request,Product $model)
  {
    $data=$request->all();
    $product_maper = array();
    //Product::where('product_id',$data['product_id'])->delete();
    if(!empty($data['location_ids'])){
      foreach($data['location_ids'] as $location_id){
        $location_id_exist = DB::table('products')->select('location_id')->where('product_id',$data['product_id'])->where('location_id',$location_id)->get();
        if(count($location_id_exist)==0){
          $product_maper[] = array(
              'location_id' => $location_id,
              'product_id' =>  $data['product_id']
          );
        }
       // $location = Product::create($product_maper);
      }
      if(count($product_maper) <>0){
        Product::insert($product_maper);
        return redirect()->route('product.index')->withStatus(__('Location successfully mapped with product.'));
      }
      return redirect()->route('product.index');
    }
    return redirect()->route('product.index')->withStatus(__('No location not mapped with that product.'));
  }

  public function destroy($location_id,Request $request)
  {
      $product_id = $request->query('product_id');
      Product::where('product_id',$product_id)->where('location_id',$location_id)->delete();
      return redirect()->route('product.index')->withStatus(__('Mapped Location Deleted Successfully.'));
  }
  public function getShopifyObject()
  {
    return Shopify::setShopUrl($this->shop_url)->setAccessToken($this->password);
  }    
}

resources/views/product/create.blade.php
@extends('layouts.app', ['page' => __('Location Management'), 'pageSlug' => 'product'])

@section('content')
<div class="row screen-location-page member-ship-page  Add-Locations-page">
  <div class="col-md-12">
    <div class="card ">
      <div class="card-header header-section-manage-location">
        <div class="row">
          <div class="col-8">
            <h2 class="card-title"><img src="{{ asset('black') }}/img/Location-icon.png" class="add-location"> {{ __('Add Locations') }}</h2>
          </div>
        </div>
      </div>
      <div class="card-body">
        @include('alerts.success')
        <div class="row">
          <div class="col-12 manage-border">
            <h4 class="card-title heading-member-color">{{ $product_name }}</h4>
          </div>
        </div>
        
        <div class="row activeinactive add-location-page-screen">
          <div class="col-6 form-group active-group input-member-plan">
            <i class="fa fa-search" aria-hidden="true"></i>
            <input type="text" name="search_location" id="search_location" class="form-control form-control-alternative" placeholder="{{ __('Search Location..') }}" value="{{ old('search_location') }}">
          </div>
            <div class="col-md-6 active-group MEMBERSHIP-plan">
              <div class="form-group">
                <input type="radio" id="test3" name="location_status" class="l location_status" value="Active" checked="checked">
                <label for="test3">Active</label><span class="button-border">|</span>
                <input type="radio" id="test4" name="location_status" class="location_status" value="Inactive"> 
                <label for="test4">Inactive</label><span class="button-border">|</span>  
                 <button type="submit" class="btn btn-success btn-search mt-4">{{ __('SEARCH') }}</button>
              </div>
            </div> 
        </div>

        <div class="table-screen-page manage-border-mamber">
          <form method="post" action="{{ route('product.store') }}">
            @csrf
            <input type="hidden" name="product_id" value='{{ $product_id }}'>
            <div class="table-responsive">
              <table class="table tablesorter add-location-table" id="">
                <thead class=" text-primary">
                  <th >{{ __('LOCATION') }}</th>
                  <th ></th>
                
                </thead>
                <tbody id="active-locations-list" class="table-location"></tbody>
                <tbody id="inactive-locations-list" class="table-location" ></tbody>
              </table>
            </div>
            <div class="text-Left">
              <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
              <a  href="{{ route('product.index') }}" type="button" class="btn btn-danger mt-4">{{ __('Cancel') }}</a>
            </div>
          </form>
        </div>
      </div>  
    </div>
  </div>
</div>

<script type="text/javascript">
  $("#active-locations-list").css("display", "block");
  $("#inactive-locations-list").css("display", "none");
  var map_location_id = @json($map_location_id);
  var inactive_loc_list = @json($inactive_location_list); 
  var active_loc_list = @json($active_location_list); 
  var active_location = "";
  var inactive_location = "";
  $.each(active_loc_list, function (key, val) {
    active_location +="<tr><td class='form-group-checkbox'><input type='checkbox' id='"+val.id+"'  class='location' name='location_ids[]' value='"+val.id+"' ><label for='"+val.id+"'></label></td><td><b>"+val.center_name+"</b> <br>"+val.address+", "+val.city+", "+val.state+"</td></tr>";
  });
  $.each(inactive_loc_list, function (key, val) {
    inactive_location +="<tr><td class='form-group-checkbox'><input type='checkbox' id='"+val.id+"' class='location' name='location_ids[]' value='"+val.id+"'><label for='"+val.id+"'></label></td><td><b>"+val.center_name+"</b> <br>"+val.address+", "+val.city+", "+val.state+"</td></tr>";
  });  

  $("#active-locations-list").html(active_location);
  $("#inactive-locations-list").html(inactive_location);

  $(".location_status").click(function(e){
    var radioValue = $("input[name='location_status']:checked").val();
    if(radioValue=="Active"){
      $("#active-locations-list").css("display", "block");
      $("#inactive-locations-list").css("display", "none");
    }else{
      $("#active-locations-list").css("display", "none");
      $("#inactive-locations-list").css("display", "block"); 
    }
  });

  $(".btn-search").click(function(e){
    var searchValue = $("#search_location").val();
    searchValue =  new RegExp(searchValue,'gi');
    var radioValue = $("input[name='location_status']:checked").val();
    if(radioValue=="Active"){
      var search_act_loc ="";
      console.log(searchValue);
      $.each(active_loc_list, function (key, val) {
        if (val.center_name.match(searchValue)) {
          search_act_loc +="<tr><td class='form-group-checkbox'><input type='checkbox' id='"+val.id+"'  class='location' name='location_ids[]' value='"+val.id+"' ><label for='"+val.id+"'></label></td><td><b>"+val.center_name+"</b> <br>"+val.address+", "+val.city+", "+val.state+"</td></tr>";
        }
      });
      $("#active-locations-list").html(search_act_loc);
    }else{
      var search_inact_loc ="";
      $.each(inactive_loc_list, function (key, val) {
        if (val.center_name.match(searchValue)) {
        search_inact_loc +="<tr><td class='form-group-checkbox'><input type='checkbox' id='"+val.id+"' class='location' name='location_ids[]' value='"+val.id+"'><label for='"+val.id+"'></label></td><td><b>"+val.center_name+"</b> <br>"+val.address+", "+val.city+", "+val.state+"</td></tr>"; 
        }
      });
      $("#inactive-locations-list").html(search_inact_loc);
    }
    $.each(map_location_id, function (key, val) {
      $("#"+val.location_id).prop( "checked", true );
    });
  });

  $.each(map_location_id, function (key, val) {
    $("#"+val.location_id).prop( "checked", true );
  });

</script>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.app', ['page' => __('Location Management'), 'pageSlug' => 'product'])

@section('content')
  <div class="container-fluid mt--7">
    <div class="row">
      <div class="col-xl-12 order-xl-1">
        <div class="card">
          <div class="card-header">
            <div class="row align-items-center">
              <div class="col-8">
                <h3 class="mb-0">{{ __('Locations') }}</h3>
              </div>
              <div class="col-4 text-right">
                <a href="{{ route('location.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
              </div>
            </div>
          </div>
          <div class="card-body">
            <form method="post" action="{{ route('location.update', $location) }}" autocomplete="off">
              @csrf
              @method('put')

            <h6 class="heading-small text-muted mb-4">{{ __('Location information') }}</h6>
            <div class="pl-lg-4">
                <div class="form-group{{ $errors->has('center_name') ? ' has-danger' : '' }}">
                  <img src="{{ asset('black') }}/img/center-name.png" class="add-location-form">
                  <label class="form-control-label" for="input-center_name">{{ __('Center Name') }}</label>
                  <input type="text" name="center_name" id="input-center_name" class="form-control form-control-alternative{{ $errors->has('center_name') ? ' is-invalid' : '' }}" placeholder="{{ __('Center Name') }}" value="{{ old('center_name', $location->center_name) }}" required autofocus>
                  @include('alerts.feedback', ['field' => 'center_name'])
                </div>
                <div class="form-group{{ $errors->has('address') ? ' has-danger' : '' }}">
                  <img src="{{ asset('black') }}/img/state.png" class="add-location-form">
                  <label class="form-control-label" for="input-address">{{ __('Address') }}</label>
                  <input type="text" name="address" id="input-address" class="form-control form-control-alternative{{ $errors->has('address') ? ' is-invalid' : '' }}" placeholder="{{ __('Address') }}" value="{{ old('address', $location->address) }}" required>
                  @include('alerts.feedback', ['field' => 'address'])
                </div>
                <div class="form-group{{ $errors->has('city') ? ' has-danger' : '' }}">
                  <img src="{{ asset('black') }}/img/state.png" class="add-location-form">
                  <label class="form-control-label" for="input-city">{{ __('City') }}</label>
                  <input type="text" name="city" id="input-city" class="form-control form-control-alternative{{ $errors->has('city') ? ' is-invalid' : '' }}" placeholder="{{ __('City') }}" value="{{ old('city', $location->city) }}" required>
                  @include('alerts.feedback', ['field' => 'city'])
                </div>
                <div class="form-group{{ $errors->has('state') ? ' has-danger' : '' }}">
                  <img src="{{ asset('black') }}/img/state.png" class="add-location-form">
                  <label class="form-control-label" for="select-state">{{ __('State') }}</label>
                  <select name="state" id="input-state" class="form-control form-control-alternative{{ $errors->has('state') ? ' is-invalid' : '' }}" >
                  <option value=''>Select State</option> 
                  @foreach ($state_list as $list)  
                    @if($location->state == $list)
                    <option value='{{ $list }}' selected >{{ $list }}</option>
                    @else
                     <option value='{{ $list }}' >{{ $list }}</option>
                    @endif
                  @endforeach
                  </select>    
                    @include('alerts.feedback', ['field' => 'state'])
                </div>
                <div class="form-group{{ $errors->has('pincode') ? ' has-danger' : '' }}">
                  <label class="form-control-label" for="input-pincode">{{ __('Pincode') }}</label>
                  <input type="text" name="pincode" id="input-pincode" class="form-control form-control-alternative{{ $errors->has('pincode') ? ' is-invalid' : '' }}" placeholder="{{ __('Pincode') }}" value="{{ old('pincode', $location->pincode) }}" >
                  @include('alerts.feedback', ['field' => 'pincode'])
                </div>
                <div class="text-center">
                  <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/product/index.blade.php
@extends('layouts.app', ['page' => __('Location Management'), 'pageSlug' => 'product'])

@section('content')  
<div class="row screen-location-page product-page-screen">
  <div class="col-md-12">
    <div class="card ">
      <div class="card-header header-section-manage-location">
        <div class="row">
          <div class="col-8">
            <h4 class="card-title "><img src="{{ asset('black') }}/img/product.png" class="add-location">{{ __('Products') }}</h4>
          </div>
          <div class="col-4 text-right">
            
          </div>
        </div>
      </div>
      <div class="card-body">
        @include('alerts.success')
        <div class="row">
          <div class="col-12 manage-border">
            <h4 class="card-title product-heading">{{ __('PRODUCTS LIST') }}</h4>
          </div>
        </div>
        <div class="table-screen-page">
          <div class="table-responsive">
          <table class="table tablesorter " id="">
            <thead class=" text-primary">
              <th class="product-table" scope="col">{{ __('Product Name') }}</th>
              <th class="location-table" scope="col">{{ __('Locations') }}</th>
              <th class="action-table" scope="col">{{ __('Action') }}</th>
            </thead>
            <tbody>
              @foreach ($shopify_products as $key=>$product)
              
              <tr>
                <td>{{ $product->title }}</td>
                <td class="product-location-details"> 
                  @if(isset($product->location_details))
                    @foreach ($product->location_details as $location)
                    <form class="details-form" action="{{ route('product.destroy', $location->location_id) }}?product_id={{$product->id}}" method="post">
                    @csrf
                    @method('delete')
                    {{$location->center_name}}
                    <a  title='Delete Mapped Location' class="tim-icons icon-trash-simple delet-icon" data-toggle='tooltip' onclick="confirm('{{ __("Are you sure you want to delete this Mapped Location?") }}') ? this.parentElement.submit() : ''"><i></i></a>
                    </form>
                    @endforeach
                  @endif
                </td>
                <td class="add-product-table"> 
                   <a  href="{{ route('product.create') }}?product_id={{$product->id}}&product_name={{$product->title}}"  title='Add Product' data-toggle='tooltip'><img src="{{ asset('black') }}/img/Location-icon.png" class="add-location"></a>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
        </div>
      </div>
      <div class="card-footer py-4">
        <nav class="d-flex justify-content-end" aria-label="...">
       
        </nav>
      </div>

    </div>
  </div>
</div>
@endsection